### ISSUE TITLE
Email inputs should be type `email` not type `text`

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/blueprint#10]
Is there a way to easily set the input type? 

Email inputs used on the portal should be type `email` not `text` so they activate the email keyboard on mobile devices. 

https://www.dropbox.com/s/ptkicxn5a406oli/Screenshot%202019-03-18%2010.54.14.png?dl=0

**Comment by rin** [comment]
yep, the `input` component in blueprint already uses the `type` proptype, see here: https://github.com/aimementoring/blueprint/blob/master/src/lib/components/input/input.js#L63 so changes only need to be made in portal, not here.

**Comment by mischacolley** [comment]
Thanks @rin ... I'll file that one away in memory :)
