### ISSUE TITLE
Force consistent appearance for date input

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/blueprint#11]
iOS styles the date input which looks weird when all the other inputs look one way. Need to force it to look like a standard input. 

![IMG_0DD6665CD9B4-1](https://user-images.githubusercontent.com/608225/54501381-1b55f780-4979-11e9-989d-53f07dcba67b.jpeg)

Temp fix added to portal but should be done here 

https://codepen.io/moaazsidat/pen/KprNLZ

@lulen11 I'd consider adding `-webkit-appearance: textfield;` and `-moz-appearance: textfield;` as a reset.

**Comment by lulen11** [comment]
Should we do this at Blueprint level @mischacolley ?

**Comment by mischacolley** [comment]
@lulen11 yes

**Comment by lulen11** [comment]
🤦‍♀️Ignore me! I thought this issue was in the portal project. 😬
