### ISSUE TITLE
Create "Imagine whats possible" section

### ISSUE THREAD

**Issue by kbardi** [aimementoring/blueprint#115]
Add background image section.
Create SVG or GIF for overlapped images.
Create custom title.

[Design](https://www.figma.com/file/TEcL59OSu2O8ays1KeNaRIDS/Homepage-%26-Navigation?node-id=471%3A0)

![image](https://user-images.githubusercontent.com/4523375/69982782-0673c100-1514-11ea-8ec6-880b24480776.png)

**Comment by lulen11** [comment]
Talked with @kbardi - this one is not going to be a blueprint component so closing
