### ISSUE TITLE
Style form elements in Blueprint

### ISSUE THREAD

**Issue by lulen11** [aimementoring/blueprint#12]
Look to style form elements in Blueprint and then removing unnecessary styling off the portal (and website) 

Look at all form elements but in particular: 

- [x] textareas
- [ ] intl phone inputs
- [x] multi-select dropdowns
- [x] buttons - navigation vs inside a form - primary vs secondary etc

**Comment by lulen11** [comment]
The phone input looks extra weird all of a sudden (but may go away once we merge the latest PRs) 

<img width="1680" alt="Screen Shot 2019-03-18 at 5 23 35 pm" src="https://user-images.githubusercontent.com/39749772/54510731-a4cdef80-49a2-11e9-87c5-183f80a4ec76.png">

Putting here to address as 1st priority

**Comment by mischacolley** [comment]
@lulen11 FYI for more discussion 

- textarea should be good now
- int phone input has had styles added to portal to make it work but need to work out how to style from blueprint 
- I've styled the fonts of the react-selects now and now how to style some other bits too

**Comment by mischacolley** [comment]
Closing as there is a seperate issue for the phone input https://github.com/aimementoring/blueprint/issues/21
