### ISSUE TITLE
Style error messages in Blueprint

### ISSUE THREAD

**Issue by lulen11** [aimementoring/blueprint#13]
Using this design as the basis, style error messages in blueprint to work across the portal and website. 

<img width="533" alt="Screen Shot 2019-03-18 at 1 23 16 pm" src="https://user-images.githubusercontent.com/39749772/54502900-05e4cb80-4981-11e9-842d-8ae7389a82dd.png">

**Comment by mischacolley** [comment]
Closing in favour of https://github.com/aimementoring/blueprint/issues/1
