### ISSUE TITLE
Improve Button markup

### ISSUE THREAD

**Issue by lulen11** [aimementoring/blueprint#208]
If we don't set a `containerClassName` on the `Button` component, the output sets the class as `undefined`. Perhaps we can set some standard container styles or find a way for the container not to set an  undefined class if we don't  set one. 

More from Cris on Slack [here](https://aimementoring.slack.com/archives/GB1SEFXST/p1590114192058900).

**Comment by rin** [comment]
This has been fixed in https://github.com/aimementoring/blueprint/pull/200/files but is not in master and not released yet.
