### ISSUE TITLE
Allow links within list items in List component

### ISSUE THREAD

**Issue by lulen11** [aimementoring/blueprint#210]
How can we add a link within [List](http://blueprint.aimementoring.com/#list) components?  

Eg. 

```
<List type="ulList" list={[
  'Item 1', 
  'Item 2 with <a href="#">link</a>', 
  'Item 3', 
  'Item 4'
]} /
```

**Comment by rin** [comment]
Sorry, Lara, we really did this component in a weird way – it should of course accept children 😅 . I'm fixing it!
