### ISSUE TITLE
Limit changed files being committed to repo 

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/blueprint#22]
Hey all,

Currently we are tracking in git and also committing a lot of files that make authoring on blueprint noisy. Especially if you are doing a lot of smaller changes and want someone to review just those things. These included things like: 

- `coverage/...`
- `styleguide/precache-manifest..` and the versioned css files

You can be selective in what you commit but I don't like to have to think about that :) and ideally I see us git ignoring most of these files ... What am I missing??

@kbardi wann outline why it was setup this way as you told me and then we can all help workout the best solution moving forward ...

**Comment by mischacolley** [comment]
@kbardi I think I remember hearing you say something the other day that made me think this might not be an issue any more? Can we close it?

**Comment by kbardi** [comment]
Remove coveralls folder...about styleguide, we need a different repo if we do not want to push those changes all the time, or maybe push those files to S3 on amazon when running a deploy...
