### ISSUE TITLE
Enhance Video Component

### ISSUE THREAD

**Issue by rin** [aimementoring/blueprint#24]
https://www.dropbox.com/s/67dq409niwyae79/Screenshot%202019-03-13%2023.06.13.png?dl=0

**Comment by mischacolley** [comment]
Hey @rin just fleshing out your list from above a bit more. This is some of what I'm thinking. @charliemckenzie can you also include an example design of what you are looking at for videos on the website please ...

- [ ] Ability to control design of cover image. So yep rounded corners, hide controls etc etc could be at play. 
- [ ] Pull cover image automatically from video if possible. Allow for custom override prop to be provided maybe? 
- [ ] Custom play button
- [ ] Preferable that we can control the player controls etc in our own custom video rather then embedding a youtube or vimeo iframe
- [ ] Ability to play inline and playing like on the website, dimming the background I think ...
- [ ] Consider where our videos are going to live. Do we keep them on the [media api and pull in from there](https://github.com/aimementoring/website/issues/51)?  
- [ ] Support for HLS streaming. i.e. [this is the Vimeo format](https://player.vimeo.com/external/326229385.m3u8?s=ccd4312c26f7981d8bcac17bb0bfd10584cfc150) but maybe we should research any others so we can support other things?  
- [ ] Subtitle support (via our Media API?)
- Even with videos potentially from our own API we may want to bring in Youtube videos we don't own to sunday kindness posts etc. Have also seen Katie try to use Facebook ones...

**Comment by rin** [comment]
So, I've done another comparison between `videojs` and `react-player`. 
I think `react-player` is best for videos from a lot of different platforms and when you don't care too much about how your player looks, while `videojs` is best if you want to style your player and play your own videos.

My main problem with `react-player` is that it is very difficult to style. Because I'm not exactly known to be a CSS magician, I would appreciate somebody else having a look, though. Maybe @kbardi ? (Kevin, if there were specific reasons why you wanted to use `react-player`, please add your comments.)

About the iFrame – youtube videos will technically use an iFrame, but that doesn't mean you can't customise the play button etc (you can still hide the youtube player controls, and probably even the youtube logo by passing some options).

My questions would be:
1. **Did we actually have any real problems** with `videojs` apart from it not working that well together with React (which we were able to work around, so it's not a concern anymore) and causing a lot of obscure issues in Bugsnag (which might be the same for any other player – especially with mobile browsers)?

2. Are we mostly using our own videos from the media-api or S3 or hosted on vimeo? I think for all of the content apart from potential Sunday Kindness videos, we are …? 

Trying to think of where we will use videos, I guess it's mostly to educate people about AIME ("About AIME" section on the website, training for new mentors), so that will be our own videos, and only very few "external" videos (especially because these could be deleted or replaced with other videos, so we don't control that content?).

**Comment by rin** [comment]
(Sorry, accidental click!)

**Comment by charliemckenzie** [comment]
I don't think the player has to be styled tooo crazily. Even if it's just pretty standard to start with that's fine with me :) as long as it is possible to style it in the future hahaha. In terms of what videos will look like on the website, that's a good question. I've attached a pic from the homepage, where ultimately, Id also like the video thumbnail to be the background of the section (again, if that's too crazy we can come up with something else hahaha)
<img width="826" alt="Screen Shot 2019-04-04 at 7 31 05 am" src="https://user-images.githubusercontent.com/39502831/55514659-07660180-56ac-11e9-9b64-b2f29ca6f542.png">

To be honest, I was thinking of keeping it pretty simple with the videos. Kinda like a variation on this (i love the scrubber preview though <3

<img width="933" alt="Screen Shot 2019-04-04 at 7 36 50 am" src="https://user-images.githubusercontent.com/39502831/55514851-7fccc280-56ac-11e9-8bd7-b9ec955bd297.png">

As for where the videos will be... they'll be everywhere hahaha. Jack loves his videos, and I think they really do convey AIME's personality well. Challenge is we'll need to make this accessible to everyone, which is a struggle when even Australia has shite internet hahaha.

**Comment by mischacolley** [comment]
@rin yay sketches :)

Thanks for adding so much detail here crew! 

So I've had a dive into the docs for react-player and I don't think styling should actually be too difficult. 

i.e. here is an example of using a HLS streaming url and I've added some basic custom content/styles around the video player https://jsfiddle.net/uk18v6Ls/14/ // We'd need to build this sort of structure into ours and then should also be able to support inline and popup players I'd think. 

What I wasn't able to get working while looking at this was a custom play button with thumbnail/cover initially hiding the controls. But we totally should be able to get this sort of thing working with the `light` prop but I couldn't spend the time to figure it out. @rin @kbardi this might be enough info for you to pick that up? 

I found this really helpful to look at all the options https://cookpete.com/react-player/

**Comment by mischacolley** [comment]
@rin I also wasn't able to get the vimeo m3u links working with the demo player. Saw your PR on the repo but also this https://github.com/CookPete/react-player/issues/423

**Comment by rin** [comment]
@mischacolley haha awesome, how come I didn't find that second link? I was wondering whether I could force the player to treat is just as a file, but didn't investigate it further. So I'd say we can make it work and the open issue is not a show stopper.

I think we should try to get the custom play button to work without the `light` mode, because as I said here https://github.com/aimementoring/aime-portal/pull/168#issue-262951397 (see the gif!), in the light mode the player is only loaded when you click the play button, and then you have to click play again to actually play it, and that feels not very usable and … cumbersome? 🥒   

So, as for next steps I wonder if we should
1. Do a very basic, minimalistic video player component, like the one in @charliemckenzie's second screenshot …, and then …
2. Try to build what's in Charlie's first screenshot, preferably without the `light` player but let's see.

I don't know how strong @kbardi s CSS game is, but I know I don't know how to do the custom play button because I've already tried :) . I can get started and then leave the styling to the pros.

We already have a video player component in Blueprint now, but in the styleguide it's used with vimeo and youtube, so it just looks like a vimeo/youtube player right now.

**Comment by mischacolley** [comment]
@rin  👍🏼

Re `light` mode. Sounds like I may be totally wrong but I'd assume in light mode that the custom play button could be setup to trigger the play in autoplay mode and avoid the double click? 

1 & 2). 👍🏼If the button functionality is there I can totally help with basic styles for it :)

**Comment by rin** [comment]
So, the player looks like this if we're just playing a file:

<img width="661" alt="Screen Shot 2019-04-08 at 17 34 50" src="https://user-images.githubusercontent.com/294558/55738685-dda03800-5a27-11e9-9fc2-f6f887fca9fe.png">

We can make it even cleaner by removing the current and total time (this works in Chrome: 
`video::-webkit-media-controls-current-time-display, video::-webkit-media-controls-time-remaining-display {
  display: none;
}`).

**Comment by lulen11** [comment]
@bronz3beard is now working on updating this video component with assistance from @kbardi  & @rin & @lulen11 ) - 
1. working to get the video component in blueprint / contentful
2. Styling
- Adding the svg custom buttons
- Getting the video component to behave the same across platforms

**Comment by rin** [comment]
Had to read up on this whole issue because it's been a while! To sum it up, I think we decided for `react-player` (see comments above on how to style it).
The biggest open question for me was, can we avoid the two clicks you need to do to play the video when using the light mode. Other than that, happy for you @bronz3beard to just experiment a little with styling, (I think we're going for a minimalistic look anyway) and usability (the mentioned two clicks …).

**Comment by rin** [comment]
Ah, and this might be helpful/interesting or maybe not: https://github.com/aimementoring/aime-portal/pull/168 @bronz3beard

**Comment by lulen11** [comment]
hey @rin and @bronz3beard were you able to connect on this one? :)

**Comment by bronz3beard** [comment]
@lulen11 I think Rin is on leave for the day, but looking to make a time for the meeting this Friday late afternoon.

**Comment by rin** [comment]
Note to self and Rory, remember to use the latest version of react player (1.14.2 I think) because an issue we had and submitted a PR for was merged and is in master now.

**Comment by lulen11** [comment]
hey @rin @bronz3beard could we please get a status checkin for this component? 

We'll need to swing back into it asap. 

Things we want to check are:
- [ ] it supports youtube links
- [ ] it supports vimeo links (including hls streaming) 
- [ ] it supports direct links to files eg .mp4 
- [ ] is it possible to support live youtube streaming embeds (ie. are they diff to normal ones?... here's an [example of bevis live streaming](https://www.youtube.com/watch?v=89qWF4rBYok) that is now over)

**Comment by bronz3beard** [comment]
@lulen11 @rin 
All of the above works I have also added two new links to test live streaming. The only thing I was not able to do is to get it to work locally, I'm hoping rin will have some luck with that.
👍

**Comment by lulen11** [comment]
Thanks @bronz3beard. I had a look for where this is component work is and I thiiiink it's on https://github.com/aimementoring/blueprint/pull/163 right? Because this is connected with https://github.com/aimementoring/blueprint/pull/31 but that's closed now. I can relink those ones but want to confirm that's right with you two...

**Comment by bronz3beard** [comment]
@lara I would say this is the issue for the pr #163 but we can add anything to this or the pr from old issues/pr that could be useful to keep logged

**Comment by lara** [comment]
@bronz3beard you tagged the wrong person man

**Comment by mischacolley** [comment]
@lulen11 @rin can this be closed / if there are remaining issues maybe we close and break out into their own issues ...

**Comment by rin** [comment]
I think we can close this and there's actually nothing open anymore …? @bronz3beard
