### ISSUE TITLE
Button styles

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/blueprint#25]
Just noting down a few more style things to do on these buttons:

- [ ] Position the button(s) in the centre of the `mrContainer`
- [ ] Fix button font styles and padding
- [ ] Style back button to be pink and next button to be purple like designs
- [ ] Once 👆 right colours are on - check hover styles

**Comment by lulen11** [comment]
Closing this as I think we now have new issues around buttons and these are less relevant
