### ISSUE TITLE
Make it easier to preview blueprint in local project 

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/blueprint#28]
Making it easier to do this https://aimementoring.slack.com/archives/GDJCPH517/p1552952436073300 will significan't speed up dev and test time

**Comment by mischacolley** [comment]
@kbardi @davidpaley not sure if this is still how things are working but improving this workflow I think would be a good thing for us to work on...

**Comment by kbardi** [comment]
added command yarn start:dev to load styleguide locally
