### ISSUE TITLE
Leverage Filestack to support Video Question direct from mobile device camera

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/blueprint#32]
Considering the push back we've had on video questions and the friction of having to first upload to Youtube I thought it might be a nice enhancement to consider creating a component that could take a URL from a youtube video but optionally allow to record directly and upload the file leveraging filestacks ability to do that on devices. 

https://www.filestack.com/products/file-upload/

Doesn't look like we can access the webcam on desktops but works on phones.

**Comment by camposcristianeze** [comment]
I know that Filestack was causing some issues on dev, especially at the time of making the fields required to the point some @aimementoring/engineering mentioned that would be interesting to change.
Now we're paying for Filestack and we have all the UI already worked out (different upload methods, integration with S3) I'm not sure if this is worth the change.

@davidpaley @kbardi any thoughts?

**Comment by mischacolley** [comment]
Yep I'd love to know what the issues where ... I think the benefit to not having to build out something 100% ourselves here is high.

**Comment by mischacolley** [comment]
@charliemckenzie can you wireframe the idea for this one along with support text as discussed and how you see it working. If you test https://www.filestack.com/products/file-upload/ on mobile you should see how it works and get an idea of if the UX feels good. If someone had shot elsewhere and uploaded to youtube I think this component could still take a URL. Once you've had a bit of a think about this can you look in @davidpaley and @kbardi as we could move on the build of this seperate to the rest of the application layout etc :)

**Comment by mischacolley** [comment]
Instead of doing just:

<img width="640" alt="Screenshot 2019-07-29 11 46 27" src="https://user-images.githubusercontent.com/608225/62016624-88ff1380-b1f6-11e9-94ed-edf3642b331d.png">

We wanna be able to do something more like:

<img width="765" alt="Screenshot 2019-07-29 11 47 13" src="https://user-images.githubusercontent.com/608225/62016644-a03e0100-b1f6-11e9-81e9-a524063f3600.png">

The two blockers we've had with people completing this step have been: 

A) Cultural. People being too shy/scared/nervous to record a video. We can overcome this one with better framing of why getting outside your comfort zone is an important first step at AIME and why/how we use this info. 
B) Technological. We wanna remove the technical difficult some people have had by giving them the simple option to record and upload directly from their device (hopefully in just a few clicks) alongside still being able to add a link to the video file if that's the way they did it. 

@davidpaley I'm keen to get you to have a look at how you might accomplish the idea @charliemckenzie has out forward here with something like Filestack.

**Comment by mischacolley** [comment]
@davidpaley the implementation of this only exists on the portal right? Should we close this (because it's done) and create another issue to migrate to Blueprint?
