### ISSUE TITLE
Enhance Title component 

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/blueprint#45]
Not sure if we should have multiple `title` components or just the one with more options as defined below...

- Right now the title component is a `div` and `span` when they should be a h1 through h6 heading. So `type` should be independent of `style` and even `size`. I don't think there is ever a case the title shouldn't be a h1-h6 heading.
- I'd propose adding a `style` prop with `gradient`, `blockTitle`, `mainTitle` etc etc. 
- I'd propose adding a `size` prop with something like `xxxl`, `xxl`, `xl', `l`, `m`, `s`, `xs`, `xxs`, `xxxs`. // May be a better way to go but it's a suggestion ...

**Comment by lulen11** [comment]
Hey @kbardi I started working on this issue but have had to pause due to my limited REACT knowledge 💔 Would love your help when we can connect - https://github.com/aimementoring/blueprint/pull/73
