### ISSUE TITLE
Input component enhancements 

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/blueprint#52]
- The input component doesn't look styled ... what are the possible themes? We should style this as we use it currently in blueprint right? 
- Should included an option with help text below
- When entering text placeholder doesn't change

**Comment by lulen11** [comment]
This has moved further along since we opened this issue but still need to further enhance input components, considering things like Prefix, postfix icons and interactions states: 

- Error styles
- Active styles
- Focus
- Disabled 
- etc
-

**Comment by lulen11** [comment]
Closing this in favour of https://github.com/aimementoring/blueprint/issues/174
