### ISSUE TITLE
Create Progress bar component

### ISSUE THREAD

**Issue by kbardi** [aimementoring/blueprint#60]
**Why is this component a good candidate for Blueprint?**
Because we need this component on Aime-portal, and it could be used from different projects. It is a small component with easy customisable attributes by theme or props.

**Describe the solution you'd like**
Progress bar component which receive background color or theme, percentage (progress), and if it should display percentage value or not, with a container to position it easily at the top of the screen.

**Describe alternatives you've considered**
If applicable a clear and concise description of any alternative solutions or features you've considered.

**Additional context**
We need it now for Hooded Scholar Application

**Comment by mischacolley** [comment]
@kbardi @charliemckenzie we should look at making the "display file upload progress" style the same for [this](https://github.com/aimementoring/blueprint/issues/44) too

**Comment by kbardi** [comment]
Progress bar is already created...I think we can use the same one but update the percentage according to upload progress...can we close this issue @mischacolley ?
https://blueprint.aimementoring.com/#progressbar
