### ISSUE TITLE
Create PDF Viewer with Accept Terms and conditions

### ISSUE THREAD

**Issue by kbardi** [aimementoring/blueprint#61]
**Why is this component a good candidate for Blueprint?**
We need this component in multiple places, and it would be great to have a component with some props to display everything.

**Describe the solution you'd like**
A new component in blueprint with PDF link props, checkbox text, and action on accepted as optional param.

**Additional context**
We already need this on Hooded Scholar Application

**Comment by camposcristianeze** [comment]
Isn't this the same as https://github.com/aimementoring/blueprint/issues/59 ?

**Comment by kbardi** [comment]
Approved and merged
