### ISSUE TITLE
Create Base Theme and set as blueprint default

### ISSUE THREAD

**Issue by lulen11** [aimementoring/blueprint#71]
Hey team, 

First step of updating themes, let's create `baseTheme` (I think this name or maybe `foundationTheme` is more suited than `wireframeTheme` @mischacolley 😀Hope you likey 🤞😃)

**Comment by lulen11** [comment]
Opened up this PR for step 1 of this: https://github.com/aimementoring/blueprint/pull/72

**Comment by mischacolley** [comment]
Closing as covered by #72 and in progress across other issues
