### ISSUE TITLE
Finalise basic components to be used in Imagination Dec MVP

### ISSUE THREAD

**Issue by lulen11** [aimementoring/blueprint#75]
Finish the following components to use in the Imagination Declaration 

- [ ] [Title](https://github.com/aimementoring/blueprint/issues/45)
- [ ] [Paragraph](https://github.com/aimementoring/blueprint/pull/69)
- [ ] Form fields
- [ ] Image
- [ ] [Dream Factory footer](https://github.com/aimementoring/blueprint/issues/74)

**Comment by mischacolley** [comment]
@lulen11 closing this as the other issues exist for them outside the context of this project
