### ISSUE TITLE
Update font family on title in Blueprint

### ISSUE THREAD

**Issue by lulen11** [aimementoring/blueprint#8]
This title component seems to be styled differently in Blueprint to how we want it to look. If you remove the font style, it pulls the portal styles and looks right.... but instead, we probably want to remove the portal styles and update in Blueprint... 

@mischacolley could you please update this one when you're in Blueprint today

<img width="1680" alt="Screen Shot 2019-03-15 at 11 29 50 am" src="https://user-images.githubusercontent.com/39749772/54400598-c36c8600-4717-11e9-95b7-a8477594247a.png">

**Comment by mischacolley** [comment]
@lulen11 once #9 is merged you can review and close :)
